import streamlit as st
from multiapp import MultiApp
# import your app modules here
from apps import paraphraseApp, summarizeApp
from paraphraser import is_generated_by_ai

st.set_page_config(
    page_title="AI GEN APP",
    page_icon="📈",
    menu_items={
        'Get Help': 'https://www.extremelycoolapp.com/help',
        'Report a bug': "https://www.extremelycoolapp.com/bug",
        'About': "# This is a header. This is an *extremely* cool app!"
    }
)

st.markdown("""
# AI GENERERATED TEXT RECOGNITION (AGTR)

AGTR provides one usefull service - Understanding if the text was generated by AI. It utilizes HuggingFace transformer model to solve the task. 

## Enter your text and see the magic!

""")

# st.title('IS GENERATED BY AI')
# st.write('Please provide the text to be analyzed')
user_input = st.text_area('Enter text','')
output = is_generated_by_ai(user_input)


st.write("Paraphrased Text: ")
st.write(f'**{output}**')

# Add all your application here
# app.add_app("Paraphraser", paraphraseApp.app)
#app.add_app("Summarizer", summarizeApp.app)
# The main app
# app.run()
