import streamlit as st
from paraphraser import is_generated_by_ai

def app():
    st.title('IS GENERATED BY AI')
    st.write('Please provide the text to be analyzed')
    user_input = st.text_area('Enter text','')
    output = is_generated_by_ai(user_input)
    st.write("Paraphrased Text: ")
    st.write(output)